### ISSUE TITLE
Lack of responsivity on some components

### ISSUE THREAD

**Issue by Nykollas** [soaple/corona-board#1]
![image](https://user-images.githubusercontent.com/22648130/75898502-e6a4af80-5e18-11ea-9726-65efa1c6266d.png)

Some components aren't responsive

My device resolution:1366x768

**Comment by Alokgoyal199555** [comment]
Hello when i run the "npm run build" its make a folder that name is "dist". 
in this folder there is no of files like 0.app.bundle , 2.app.bundle as so on....
but i want a build folder there is src folder and index.js like when we run "npm run build" on the normal project that make it.
actually i want to upload this project on my cpanel and want to see how its is working.
please help me .

**Comment by soaple** [comment]
I had fixed this bug.
Please try again :)

**Comment by Nykollas** [comment]
Great!
